feat: ProfileImage 컴포넌트, Header 컴포넌트 구현
Yoos99/NFE1-1-3-5team_Frontend pull request #5
Opened 2024-10-28 08:31 UTC by wilderif

- ProfileImage 컴포넌트 구현
- Header 컴포넌트 구현
- Header 컴포넌트에 Link 태그 활용한 페이지 이동 로직 추가
- RootLayout 컴포넌트에 Header 컴포넌트 추가 및 header, main 태그 추가
(main 태그 내부 Outlet에 각자 맡은 페이지들 구현부가 들어간다고 생각하시면 됩니다.)

2024-10-28 08:55 UTC, JW-Ahn0 requested changes
코멘트 확인 부탁드립니다~
조치하시고 자체적으로 resolve conflict 하셔도 문제 없을 것 같습니다.

2024-10-28 08:55 UTC, JW-Ahn0 commented on src/components/layout/Header/Header.tsx
>          // 우선 Button 컴포넌트를 사용하고, 텍스트 색상, 버튼 height 같은 디테일한 css는 후반부에 수정하겠습니다.
이런 부분 같은 경우는 저희끼리 TODO 주석을 명시해서 남기는 방법도 괜찮아 보이네요.
/*
  TODO: 이 클래스의 메서드를 개선해야 합니다.
  성능 향상을 위해 알고리즘을 최적화하세요.
*/

2024-10-28 08:55 UTC, JW-Ahn0 commented on src/components/common/ProfileImage/ProfileImage.styled.ts
> +  $usageType: "header" | "userInformation" | "post" | "card";
이 부분이 
' - styled component에서 $없이 prop 전달 할 때 발생하는 에러 수정' 로 보이는데
styled component 에 prop 전달할 때는 무조건 $를 써야하나요? 어떤 에러가 발생하신건지 궁금합니다.

2024-10-28 08:55 UTC, JW-Ahn0 commented on src/components/common/ProfileImage/ProfileImage.stories.tsx
> +// 원형 이미지 확인용
이 부분은 테스트 하시다가 남겨놓으신 부분 같은데 맞을까요?
맞다면 이 부분은 삭제 부탁드립니다 ㅎㅎ

2024-10-28 11:39 UTC, wilderif commented on src/components/common/ProfileImage/ProfileImage.styled.ts
> +  $usageType: "header" | "userInformation" | "post" | "card";
styled component의 prop과 react component의 prop이 혼동되어서 나오는 경고인 것 같은데, 실행은 되는데 콘솔에 경고가 나와 이렇게 수정했습니다. $로 시작하면 내부적으로 css처리를 위한 prop이라고 인식하게되는 것 같아요.

2024-10-28 11:42 UTC, wilderif commented on src/components/layout/Header/Header.tsx
>          // 우선 Button 컴포넌트를 사용하고, 텍스트 색상, 버튼 height 같은 디테일한 css는 후반부에 수정하겠습니다.
의견 반영해서 변경했습니다.

2024-10-28 12:48 UTC, aaahyesu commented
확인했습니다
추가로 수정요청드릴 것은 없는 것 같고, 로고는 단색 .svg 하나 있는 것 같은데 그라데이션 svg는 제가 따로 추가하면 되는걸까요?

2024-10-28 12:53 UTC, wilderif commented
> 확인했습니다👍 추가로 수정요청드릴 것은 없는 것 같고, 로고는 단색 .svg 하나 있는 것 같은데 그라데이션 svg는 제가 따로 추가하면 되는걸까요?

svg 파일 퍼블릭에 추가하고 LogoGradation 컴포넌트도 구현해두었는데, common -> Logo 폴더 한번 확인해 보시겠어요? 안 보이시면 말씀해주시면 다시 보겠습니다.

2024-10-28 23:13 UTC, JW-Ahn0 approved these changes

2024-10-29 00:08 UTC, ayoung26 approved these changes
코드 잘 봤습니다! 🙂

2024-10-29 00:08 UTC, merged